config/routes.rb
Rails.application.routes.draw do
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  root 'pages#home'
  
  get 'pages/about'
  get 'pages/contact'
  get 'pages/fag'

  resources :sessions, only: [:create, :destroy]  
  resources :fragrances
  resources :categories
  resources :sizes
  resources :items

end

app/models/fragrance.rb
class Fragrance < ActiveRecord::Base
    has_many :item_and_fragrances
    has_many :items, through: :item_and_fragrances
end

app/controllers/fragrances_controller.rb
class FragrancesController < ApplicationController
  before_action :set_fragrance, only: [:show, :edit, :update, :destroy]

  # GET /fragrances
  # GET /fragrances.json
  def index
    @fragrances = Fragrance.all
  end

  # GET /fragrances/1
  # GET /fragrances/1.json
  def show
  end

  # GET /fragrances/new
  def new
    @fragrance = Fragrance.new
  end

  # GET /fragrances/1/edit
  def edit
  end

  # POST /fragrances
  # POST /fragrances.json
  def create
    @fragrance = Fragrance.new(fragrance_params)

    respond_to do |format|
      if @fragrance.save
        format.html { redirect_to @fragrance, notice: 'Fragrance was successfully created.' }
        format.json { render :show, status: :created, location: @fragrance }
      else
        format.html { render :new }
        format.json { render json: @fragrance.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fragrances/1
  # PATCH/PUT /fragrances/1.json
  def update
    respond_to do |format|
      if @fragrance.update(fragrance_params)
        format.html { redirect_to @fragrance, notice: 'Fragrance was successfully updated.' }
        format.json { render :show, status: :ok, location: @fragrance }
      else
        format.html { render :edit }
        format.json { render json: @fragrance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fragrances/1
  # DELETE /fragrances/1.json
  def destroy
    @fragrance.destroy
    respond_to do |format|
      format.html { redirect_to fragrances_url, notice: 'Fragrance was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fragrance
      @fragrance = Fragrance.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fragrance_params
      params.require(:fragrance).permit(:name, :description)
    end
end

app/helpers/fragrances_helper.rb
module FragrancesHelper
end

app/views/fragrances/_form.html.erb
<%= form_for(@fragrance) do |f| %>
  <% if @fragrance.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fragrance.errors.count, "error") %> prohibited this fragrance from being saved:</h2>

      <ul>
      <% @fragrance.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fragrances/edit.html.erb
<h1>Editing Fragrance</h1>

<%= render 'form' %>

<%= link_to 'Show', @fragrance %> |
<%= link_to 'Back', fragrances_path %>

app/views/fragrances/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Fragrances</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @fragrances.each do |fragrance| %>
      <tr>
        <td><%= fragrance.name %></td>
        <td><%= fragrance.description %></td>
        <td><%= link_to 'Show', fragrance %></td>
        <td><%= link_to 'Edit', edit_fragrance_path(fragrance) %></td>
        <td><%= link_to 'Destroy', fragrance, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Fragrance', new_fragrance_path %>

app/views/fragrances/new.html.erb
<h1>New Fragrance</h1>

<%= render 'form' %>

<%= link_to 'Back', fragrances_path %>

app/views/fragrances/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @fragrance.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @fragrance.description %>
</p>

<%= link_to 'Edit', edit_fragrance_path(@fragrance) %> |
<%= link_to 'Back', fragrances_path %>