config/routes.rb
Rails.application.routes.draw do
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  root 'pages#home'
  
  get 'pages/about'
  get 'pages/contact'
  get 'pages/fag'

  resources :sessions, only: [:create, :destroy]  
  resources :fragrances
  resources :categories
  resources :sizes
  resources :items

end

app/models/category.rb
class Category < ActiveRecord::Base
    has_many :items
    
    mount_uploader :picture, ImageUploader
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @items = @category.items
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :description, :picture)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<div class="window">
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :picture %><br>
    <%= f.file_field :picture %>
    <% if f.object.picture? %>
      <%= image_tag f.object.picture.url size="200" %><br>
      <%= f.label :remove_picture %>
      <%= f.check_box :remove_picture %> 
    <% end %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div></br>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="padded">Categories</h1>

<% @categories.in_groups_of(3).each do |group| %>
  <div class="row">
      <% group.each do |category| %>
        <% if category %>
          <div class="col-sm-4 center padded">
            <%= link_to image_tag(category.picture, size: ("200")), category %><br>
            <%= link_to category.name, category, class: "center h2"%>
            <br>
          </div>
        <% end %>
      <% end %>
  </div>
<% end %>

<%= link_to 'New category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<h1 class="padded"><%=@category.name%></h1>

<% @items.in_groups_of(3).each do |group| %>
  <div class="row">
      <% group.each do |item| %>
        <% if item %>
          <div class="col-sm-4 center padded">
            <%= link_to image_tag(item.picture, size: ("200")), item %><br>
            <%= link_to item.name, item, class: "center h2"%>
            <br>
          </div>
        <% end %>
      <% end %>
  </div>
<% end %>

<%= link_to 'New Item', new_item_path %>