config/routes.rb
Rails.application.routes.draw do
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  root 'pages#home'
  
  get 'pages/about'
  get 'pages/contact'
  get 'pages/fag'

  resources :sessions, only: [:create, :destroy]  
  resources :fragrances
  resources :categories
  resources :sizes
  resources :items

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    You deserve to be pampered. 
  </small>
  <nav>
    <ul>
      <li><%= link_to "Facebook",   'https://www.facebook.com/MamaSuesHomeMadeBathProducts' %></li>
      <li><%= link_to "Twitter", '#' %></li>
      <% unless current_user %>
        <li><%= link_to "Employee", "/auth/google_oauth2", id: "sign_in" %></li>
      <% end %>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
  <div class="nav">
    <%= link_to "Mama Sue's Bath Products", root_path, id: "logo" %>
  </div>
  <div class="navbar navbar-inverse">
    <div class="container">
      <nav>
        <ul class="nav navbar-nav navbar-left">
          <li><%= link_to "Home",   root_path %></li>
          <li><%= link_to "Products",   items_path %></li>
          <li><%= link_to "Categories", categories_path %></li>
          <% if current_user %>
            <li class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" href="#"><%= current_user.name %>
              <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <% if can? :read, User %>
                  <li><%= link_to "User List", users_path %></li>
                <% end %>
                <li><%= link_to "Sign out", signout_path, id: "sign_out" %></li>
              </ul>
            </li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  
  <body>
    <%= render 'layouts/header' %>
    <div class="container-fluid">
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>